
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xforward_fcc.h"

/*
* The configuration table for devices
*/

XForward_fcc_Config XForward_fcc_ConfigTable[XPAR_XFORWARD_FCC_NUM_INSTANCES] =
{
	{
		XPAR_FORWARD_FCC_0_DEVICE_ID,
		XPAR_FORWARD_FCC_0_S_AXI_CTRL_BASEADDR
	}
};


