
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xvadd.h"

/*
* The configuration table for devices
*/

XVadd_Config XVadd_ConfigTable[XPAR_XVADD_NUM_INSTANCES] =
{
	{
		XPAR_VADD_0_DEVICE_ID,
		XPAR_VADD_0_S_AXI_CONTROL_BASEADDR
	}
};


