# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.srcs/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/fwd_fcc_test_axi_smc_0.xci
# IP: The module: 'fwd_fcc_test_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/bd_2794.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_0/bd_2794_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_1/bd_2794_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_2/bd_2794_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_3/bd_2794_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_4/bd_2794_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_5/bd_2794_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_6/bd_2794_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_7/bd_2794_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_8/bd_2794_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_9/bd_2794_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_10/bd_2794_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_11/bd_2794_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_12/bd_2794_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_13/bd_2794_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_14/bd_2794_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_15/bd_2794_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_16/bd_2794_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_17/bd_2794_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_18/bd_2794_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_19/bd_2794_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_20/bd_2794_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_21/bd_2794_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_22/bd_2794_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_1/bd_2794_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_1/bd_2794_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_2/bd_2794_arsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_3/bd_2794_rsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_4/bd_2794_awsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_5/bd_2794_wsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_6/bd_2794_bsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_10/bd_2794_s00a2s_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_11/bd_2794_sarn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_12/bd_2794_srn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_13/bd_2794_sawn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_14/bd_2794_swn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_15/bd_2794_sbn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_16/bd_2794_m00s2a_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_17/bd_2794_m00arn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_18/bd_2794_m00rn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_19/bd_2794_m00awn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_20/bd_2794_m00wn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_21/bd_2794_m00bn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fwd_fcc_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.srcs/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/fwd_fcc_test_axi_smc_0.xci
# IP: The module: 'fwd_fcc_test_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/bd_2794.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_0/bd_2794_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_1/bd_2794_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_2/bd_2794_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_3/bd_2794_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_4/bd_2794_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_5/bd_2794_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_6/bd_2794_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_7/bd_2794_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_8/bd_2794_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_9/bd_2794_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_10/bd_2794_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_11/bd_2794_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_12/bd_2794_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_13/bd_2794_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_14/bd_2794_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_15/bd_2794_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_16/bd_2794_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_17/bd_2794_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_18/bd_2794_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_19/bd_2794_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_20/bd_2794_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_21/bd_2794_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_22/bd_2794_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_1/bd_2794_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_1/bd_2794_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_2/bd_2794_arsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_3/bd_2794_rsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_4/bd_2794_awsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_5/bd_2794_wsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_6/bd_2794_bsw_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_10/bd_2794_s00a2s_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_11/bd_2794_sarn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_12/bd_2794_srn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_13/bd_2794_sawn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_14/bd_2794_swn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_15/bd_2794_sbn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_16/bd_2794_m00s2a_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_17/bd_2794_m00arn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_18/bd_2794_m00rn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_19/bd_2794_m00awn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_20/bd_2794_m00wn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/bd_0/ip/ip_21/bd_2794_m00bn_0_ooc.xdc

# XDC: /home/anubhav/xilinx_projects/nn1/nn/nn.gen/sources_1/bd/fwd_fcc_test/ip/fwd_fcc_test_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fwd_fcc_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
